[project]
name = "justlaunch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tim van Cann", email = "timvancann@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pytest>=9.0.2",
    "rich>=14.2.0",
    "textual>=6.11.0",
    "textual-dev>=1.8.0",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest-asyncio>=1.3.0",
]
